[package]
name = "middle_pan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
nix = "0.22.3"

[dependencies.x11rb]
version = "0.9.0"
features = [ "xinput", "xtest" ]